//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\DEV_MASCARELLO_2024\GIT\nx_siemens\ConjuntoX\ConjuntoXCreate.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: renato.ferreira
//              Version: NX 2312
//              Date: 06-03-2026  (Format: mm-dd-yyyy)
//              Time: 09:56 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C# source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System;
using NXOpen;
using NXOpen.BlockStyler;
using NXOpen.Display;
using Custom_Mascarello;
using System.Data;
using static NXOpen.UF.UFModlTrex;
using DataSet = System.Data.DataSet;
using NXOpen.Features;
using System.Windows.Forms;
using NXOpen.Annotations;
using NXOpen.UF;
using MySqlX.XDevAPI.Relational;
using NXOpen.Diagramming.Tables;
using NXOpen.CAE;
using System.Globalization;
using NXOpen.Assemblies;

namespace ConjuntoX
{
    public class ConjuntoXCreate
    {
        //class members
        private static Session theSession = null;
        private static UI theUI = null;
        private string theDlxFileName;
        private NXOpen.BlockStyler.BlockDialog theDialog;
        private NXOpen.BlockStyler.DrawingArea area_img;// Block type: Drawing Area
        private NXOpen.BlockStyler.Enumeration cmb_dim;// Block type: Enumeration
        private NXOpen.BlockStyler.Table table;// Block type: TableLayout
        private NXOpen.BlockStyler.Label label02;// Block type: Label
        private NXOpen.BlockStyler.Label label01;// Block type: Label
        private NXOpen.BlockStyler.Label label03;// Block type: Label
        private NXOpen.BlockStyler.DoubleBlock dim_alt;// Block type: Double
        private NXOpen.BlockStyler.DoubleBlock tol_alt;// Block type: Double
        private NXOpen.BlockStyler.Label label0;// Block type: Label
        private NXOpen.BlockStyler.DoubleBlock dim_larg;// Block type: Double
        private NXOpen.BlockStyler.DoubleBlock tol_larg;// Block type: Double
        private NXOpen.BlockStyler.Label label031;// Block type: Label
        private NXOpen.BlockStyler.DoubleBlock dim_folga;// Block type: Double
        private NXOpen.BlockStyler.DoubleBlock tol_folga;// Block type: Double
        private NXOpen.BlockStyler.Toggle invert;// Block type: Toggle
        private NXOpen.BlockStyler.Label indicador_bitola;// Block type: Label
        private NXOpen.BlockStyler.Separator separator0;// Block type: Separator
        private NXOpen.BlockStyler.Button simular;// Block type: Button
        private NXOpen.BlockStyler.Button pesquisar;// Block type: Button
        private NXOpen.BlockStyler.Button criar;// Block type: Button
        private NXOpen.BlockStyler.Tree Resultado;// Block type: Tree Control
        private List<string> result = new List<string>();


        //------------------------------------------------------------------------------
        //Constructor for NX Styler class
        //------------------------------------------------------------------------------
        public ConjuntoXCreate()
        {
            try
            {
                theSession = Session.GetSession();
                theUI = UI.GetUI();
                theDlxFileName = "ConjuntoXCreate.dlx";
                theDialog = theUI.CreateDialog(theDlxFileName);
                theDialog.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
                theDialog.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
                theDialog.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                throw ex;
            }
        }
        //------------------------------- DIALOG LAUNCHING ---------------------------------
        //
        //    Before invoking this application one needs to open any part/empty part in NX
        //    because of the behavior of the blocks.
        //
        //    Make sure the dlx file is in one of the following locations:
        //        1.) From where NX session is launched
        //        2.) $UGII_USER_DIR/application
        //        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
        //            recommended. This variable is set to a full directory path to a file 
        //            containing a list of root directories for all custom applications.
        //            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
        //
        //    You can create the dialog using one of the following way:
        //
        //    1. Journal Replay
        //
        //        1) Replay this file through Tool->Journal->Play Menu.
        //
        //    2. USER EXIT
        //
        //        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
        //        2) Invoke the Shared Library through File->Execute->NX Open menu.
        //
        //------------------------------------------------------------------------------
        public static void Main()
        {
            ConjuntoXCreate theConjuntoXCreate = null;
            try
            {
                Session theSession = Session.GetSession();
                Part workPart = theSession.Parts.Work;
                Part displayPart = theSession.Parts.Display;


                Part part1 = null;
                try
                {
                    part1 = (Part)theSession.Parts.FindObject("@DB/TPL_CJ_X/000");
                    //if (part1 != null)
                    //{
                    //    //NXMessageBox.Show("Part encontrada no display. Exibindo part.", "Atenção", MessageBoxButtons.OK, MessageBoxIcon.Information);
                     PartLoadStatus loadStatus;
                     theSession.Parts.SetDisplay(part1, true, true, out loadStatus);

                    //}


                }
                catch
                {

                    //MessageBox.Show("Part não encontrada no display. Abrindo part para exibição.", "Atenção", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                }

                if (part1 == null)
                {
                    BasePart basePart1;
                    PartLoadStatus partLoadStatus1;
                    basePart1 = theSession.Parts.OpenBaseDisplay("@DB/TPL_CJ_X/000", out partLoadStatus1);
                    part1 = (Part)basePart1;
                }
                theConjuntoXCreate = new ConjuntoXCreate();
                // The following method shows the dialog immediately
                theConjuntoXCreate.Launch();
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            finally
            {
                if (theConjuntoXCreate != null)
                    theConjuntoXCreate.Dispose();
                theConjuntoXCreate = null;
            }
        }
        //------------------------------------------------------------------------------
        // This method specifies how a shared image is unloaded from memory
        // within NX. This method gives you the capability to unload an
        // internal NX Open application or user  exit from NX. Specify any
        // one of the three constants as a return value to determine the type
        // of unload to perform:
        //
        //
        //    Immediately : unload the library as soon as the automation program has completed
        //    Explicitly  : unload the library from the "Unload Shared Image" dialog
        //    AtTermination : unload the library when the NX session terminates
        //
        //
        // NOTE:  A program which associates NX Open applications with the menubar
        // MUST NOT use this option since it will UNLOAD your NX Open application image
        // from the menubar.
        //------------------------------------------------------------------------------
        public static int GetUnloadOption(string arg)
        {
            //return System.Convert.ToInt32(Session.LibraryUnloadOption.Explicitly);
            return System.Convert.ToInt32(Session.LibraryUnloadOption.Immediately);
            // return System.Convert.ToInt32(Session.LibraryUnloadOption.AtTermination);
        }

        //------------------------------------------------------------------------------
        // Following method cleanup any housekeeping chores that may be needed.
        // This method is automatically called by NX.
        //------------------------------------------------------------------------------
        public static void UnloadLibrary(string arg)
        {
            try
            {
                //---- Enter your code here -----
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
        }

        //------------------------------------------------------------------------------
        //This method launches the dialog to screen
        //------------------------------------------------------------------------------
        public NXOpen.BlockStyler.BlockDialog.DialogResponse Launch()
        {
            NXOpen.BlockStyler.BlockDialog.DialogResponse dialogResponse = NXOpen.BlockStyler.BlockDialog.DialogResponse.Invalid;
            try
            {
                dialogResponse = theDialog.Launch();
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return dialogResponse;
        }

        //------------------------------------------------------------------------------
        //Method Name: Dispose
        //------------------------------------------------------------------------------
        public void Dispose()
        {
            if (theDialog != null)
            {
                theDialog.Dispose();
                theDialog = null;
            }
        }

        //------------------------------------------------------------------------------
        //---------------------Block UI Styler Callback Functions--------------------------
        //------------------------------------------------------------------------------

        //------------------------------------------------------------------------------
        //Callback Name: initialize_cb
        //------------------------------------------------------------------------------
        public void initialize_cb()
        {

            try
            {
                area_img = (NXOpen.BlockStyler.DrawingArea)theDialog.TopBlock.FindBlock("area_img");
                cmb_dim = (NXOpen.BlockStyler.Enumeration)theDialog.TopBlock.FindBlock("cmb_dim");
                table = (NXOpen.BlockStyler.Table)theDialog.TopBlock.FindBlock("table");
                label02 = (NXOpen.BlockStyler.Label)theDialog.TopBlock.FindBlock("label02");
                label01 = (NXOpen.BlockStyler.Label)theDialog.TopBlock.FindBlock("label01");
                label03 = (NXOpen.BlockStyler.Label)theDialog.TopBlock.FindBlock("label03");
                dim_alt = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("dim_alt");
                tol_alt = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("tol_alt");
                label0 = (NXOpen.BlockStyler.Label)theDialog.TopBlock.FindBlock("label0");
                dim_larg = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("dim_larg");
                tol_larg = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("tol_larg");
                label031 = (NXOpen.BlockStyler.Label)theDialog.TopBlock.FindBlock("label031");
                dim_folga = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("dim_folga");
                tol_folga = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("tol_folga");
                invert = (NXOpen.BlockStyler.Toggle)theDialog.TopBlock.FindBlock("invert");
                indicador_bitola = (NXOpen.BlockStyler.Label)theDialog.TopBlock.FindBlock("indicador_bitola");
                separator0 = (NXOpen.BlockStyler.Separator)theDialog.TopBlock.FindBlock("separator0");
                simular = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("simular");
                pesquisar = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("pesquisar");
                criar = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("criar");
                Resultado = (NXOpen.BlockStyler.Tree)theDialog.TopBlock.FindBlock("Resultado");


                conexao_bd conexao_Bd = new conexao_bd();
                DataSet dataSet = conexao_Bd.busca_cv_x();

                string[] tubos = new string[dataSet.Tables[0].Rows.Count];
                int index = 0;

                foreach (DataRow dRow in dataSet.Tables["tab_fam_nx"].Rows)
                {
                    tubos[index] = dRow["fam_cv"].ToString().Remove(0, 7);
                    index++;
                }
                try
                {
                    //for (int i = 10; i <= 100; i += 10)
                    //{
                    //  theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, tubos);
                    cmb_dim.SetEnumMembers(tubos);
                    //}
                    //---- Enter your callback code here -----
                }
                catch (Exception ex)
                {
                    //---- Enter your exception handling code here -----
                    theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
                }

                string[] bitola = cmb_dim.ValueAsString.ToString().Split('x');
                if (invert.Value == true)
                {
                    indicador_bitola.Label = bitola[1] + "x" + bitola[0];
                }
                if (invert.Value == false)
                {
                    indicador_bitola.Label = bitola[0] + "x" + bitola[1];
                }

                indicador_bitola.Label = bitola[0]+ "x"+bitola[1];

                area_img.Expanded = true;
                area_img.Image = @"X:\Custom_Mascarello\site_2312_1\bitmaps\x2.bmp";

                //------------------------------------------------------------------------------
                //Registration of Treelist specific callbacks
                //------------------------------------------------------------------------------
                //Resultado.SetOnExpandHandler(new NXOpen.BlockStyler.Tree.OnExpandCallback(OnExpandCallback));

                //Resultado.SetOnInsertColumnHandler(new NXOpen.BlockStyler.Tree.OnInsertColumnCallback(OnInsertColumnCallback));

                //Resultado.SetOnInsertNodeHandler(new NXOpen.BlockStyler.Tree.OnInsertNodeCallback(OnInsertNodecallback));

                //Resultado.SetOnDeleteNodeHandler(new NXOpen.BlockStyler.Tree.OnDeleteNodeCallback(OnDeleteNodecallback));

                //Resultado.SetOnPreSelectHandler(new NXOpen.BlockStyler.Tree.OnPreSelectCallback(OnPreSelectcallback));

                //Resultado.SetOnSelectHandler(new NXOpen.BlockStyler.Tree.OnSelectCallback(OnSelectcallback));

                //Resultado.SetOnStateChangeHandler(new NXOpen.BlockStyler.Tree.OnStateChangeCallback(OnStateChangecallback));

                //Resultado.SetToolTipTextHandler(new NXOpen.BlockStyler.Tree.ToolTipTextCallback(ToolTipTextcallback));

                //Resultado.SetColumnSortHandler(new NXOpen.BlockStyler.Tree.ColumnSortCallback(ColumnSortcallback));

                //Resultado.SetStateIconNameHandler(new NXOpen.BlockStyler.Tree.StateIconNameCallback(StateIconNameCallback));

                //Resultado.SetOnBeginLabelEditHandler(new NXOpen.BlockStyler.Tree.OnBeginLabelEditCallback(OnBeginLabelEditCallback));

                //Resultado.SetOnEndLabelEditHandler(new NXOpen.BlockStyler.Tree.OnEndLabelEditCallback(OnEndLabelEditCallback));

                //Resultado.SetOnEditOptionSelectedHandler(new NXOpen.BlockStyler.Tree.OnEditOptionSelectedCallback(OnEditOptionSelectedCallback));

                //Resultado.SetAskEditControlHandler(new NXOpen.BlockStyler.Tree.AskEditControlCallback(AskEditControlCallback));

                //Resultado.SetOnMenuHandler(new NXOpen.BlockStyler.Tree.OnMenuCallback(OnMenuCallback));;

                //Resultado.SetOnMenuSelectionHandler(new NXOpen.BlockStyler.Tree.OnMenuSelectionCallback(OnMenuSelectionCallback));;

                //Resultado.SetIsDropAllowedHandler(new NXOpen.BlockStyler.Tree.IsDropAllowedCallback(IsDropAllowedCallback));;

                //Resultado.SetIsDragAllowedHandler(new NXOpen.BlockStyler.Tree.IsDragAllowedCallback(IsDragAllowedCallback));;

                //Resultado.SetOnDropHandler(new NXOpen.BlockStyler.Tree.OnDropCallback(OnDropCallback));;

                //Resultado.SetOnDropMenuHandler(new NXOpen.BlockStyler.Tree.OnDropMenuCallback(OnDropMenuCallback));

                //Resultado.SetOnDefaultActionHandler(new NXOpen.BlockStyler.Tree.OnDefaultActionCallback(OnDefaultActionCallback));

                //------------------------------------------------------------------------------
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
        }

        //------------------------------------------------------------------------------
        //Callback Name: dialogShown_cb
        //This callback is executed just before the dialog launch. Thus any value set 
        //here will take precedence and dialog will be launched showing that value. 
        //------------------------------------------------------------------------------
        public void dialogShown_cb()
        {
            try
            {
                Resultado.InsertColumn(0, "Codigo", 200);
                //theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, "aaaaa"+result.Count().ToString());
                foreach (string res in result)
                {
                    NXOpen.BlockStyler.Node myNode = Resultado.CreateNode(res);
                    Resultado.InsertNode(myNode, null, null, NXOpen.BlockStyler.Tree.NodeInsertOption.Last);
                }
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
        }

        //------------------------------------------------------------------------------
        //Callback Name: update_cb
        //------------------------------------------------------------------------------
        public int update_cb(NXOpen.BlockStyler.UIBlock block)
        {
            try
            {
                if (block == area_img)
                {
                    //---------Enter your code here-----------
                }
                else if (block == cmb_dim)
                {
                    string[] bitola = cmb_dim.ValueAsString.ToString().Split('x');
                    if (invert.Value == true)
                    {
                        indicador_bitola.Label = bitola[1] + "x" + bitola[0];
                    }
                    if (invert.Value == false)
                    {
                        indicador_bitola.Label = bitola[0] + "x" + bitola[1];
                    }

                    _simular();

                    //---------Enter your code here-----------
                }
                else if (block == label02)
                {
                    //---------Enter your code here-----------
                }
                else if (block == label01)
                {
                    //---------Enter your code here-----------
                }
                else if (block == label0)
                {
                    //---------Enter your code here-----------
                }
                else if (block == dim_larg)
                {
                    //---------Enter your code here-----------
                }
                else if (block == tol_larg)
                {
                    //---------Enter your code here-----------
                }
                else if (block == label03)
                {
                    //---------Enter your code here-----------
                }
                else if (block == dim_alt)
                {
                    //---------Enter your code here-----------
                }
                else if (block == tol_alt)
                {
                    //---------Enter your code here-----------
                }
                else if (block == label031)
                {
                    //---------Enter your code here-----------
                }
                else if (block == dim_folga)
                {
                    //---------Enter your code here-----------
                }
                else if (block == tol_folga)
                {
                    //---------Enter your code here-----------
                }
                else if (block == invert)
                {
                    string[] bitola = cmb_dim.ValueAsString.ToString().Split('x');
                    if (invert.Value == true)
                    {
                        indicador_bitola.Label = bitola[1] + "x" + bitola[0];
                    }
                    if (invert.Value == false)
                    {
                        indicador_bitola.Label = bitola[0] + "x" + bitola[1];
                    }
                    _simular();
                   // Dispose();

                   // return 0;

                    // ---------Enter your code here-----------
                }
                else if (block == indicador_bitola)
                {
                    //---------Enter your code here-----------
                }
                else if (block == separator0)
                {
                    //---------Enter your code here-----------
                }
                else if (block == simular)
                {
                    _simular();
                }
                else if (block == pesquisar)
                {
                    _pesquisar();
                }
                else if (block == criar)
                {

                    _criar();
                    //---------Enter your code here-----------
                }
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
           
            return 0;
        }
        public int _criar()
        {
            int errorCode = 0;
            try
            {
                //errorCode = apply_cb();
                bool exist = false;
                while (Resultado.RootNode != null)
                {
                    Resultado.DeleteNode(Resultado.RootNode);
                }

                metodosX.aplicar_config(cmb_dim.ValueAsString.ToString(), dim_larg.Value.ToString().Replace(",", "."), dim_alt.Value.ToString().Replace(",", "."), dim_folga.Value.ToString().Replace(",", "."));

                if (invert.Value)
                {
                    metodosX.invert("Invertido", "1");
                }
                else
                {
                    metodosX.invert("Arrangement 1", "0");

                }

                result.Clear();
                DataSet busca = metodosX.busca_x(cmb_dim.ValueAsString.ToString(), dim_larg.Value.ToString().Replace(",", "."), dim_alt.Value.ToString().Replace(",", "."), dim_folga.Value.ToString().Replace(",", "."), invert.Value);
           

                foreach (DataRow dRow in busca.Tables[0].Rows)
                {

                    result.Add(dRow["codigo"].ToString());
                    exist = true;

                }
                if (exist == false)
                {
                    DialogResult pergunta = MessageBox.Show("Nenhum item encontrado com as configurações selecionadas, deseja criar um novo item?","Criar Conjunto X" , MessageBoxButtons.YesNo, MessageBoxIcon.Information);
                    if (pergunta == DialogResult.Yes)
                    {
                        if (invert.Value)
                        {
                            arrangement_definicao("Invertido", "Arrangement 1");
                        }
                        else
                        {
                            arrangement_definicao("Arrangement 1", "Invertido");
                        }

                        string item = metodosX.criarX(cmb_dim.ValueAsString.ToString(), dim_larg.Value.ToString().Replace(",", "."), dim_alt.Value.ToString().Replace(",", "."), dim_folga.Value.ToString().Replace(",", "."), invert.Value);
                        NXOpen.BlockStyler.Node myNode = Resultado.CreateNode(item);
                        Resultado.InsertNode(myNode, null, null, NXOpen.BlockStyler.Tree.NodeInsertOption.Last);
                        restaurar_pasta();
                        
                    }
                }


                //---- Enter your callback code here -----
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                errorCode = 1;
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return errorCode;
        }
        public void arrangement_definicao(string arrangement_manter, string arragement_del)
        {
            NXOpen.Session theSession = NXOpen.Session.GetSession();
            NXOpen.Part workPart = theSession.Parts.Work;
            NXOpen.Part displayPart = theSession.Parts.Display;
            // ----------------------------------------------
            //   Menu: Assemblies->Arrangements...
            // ----------------------------------------------
            NXOpen.Session.UndoMarkId markId1;
            markId1 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Edit Assembly Arrangements");

            NXOpen.Assemblies.Arrangement[] arrangements1;
            workPart.ComponentAssembly.RootComponent.GetArrangements(out arrangements1);

            

            NXOpen.Session.UndoMarkId markId2;
            markId2 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Set Assembly Arrangement");

            NXOpen.Assemblies.Arrangement arrangement2 = ((NXOpen.Assemblies.Arrangement)workPart.ComponentAssembly.Arrangements.FindObject(arrangement_manter));
            workPart.ComponentAssembly.RootComponent.SetUsedArrangement(arrangement2);

            theSession.DeleteUndoMark(markId2, null);

            workPart.ComponentAssembly.SetDefault(arrangement2);

            NXOpen.Assemblies.Arrangement arrangement1;
            arrangement1 = ((NXOpen.Assemblies.Arrangement)workPart.ComponentAssembly.Arrangements.FindObject(arragement_del));
            
            arrangement1.Delete(true);

            theSession.CleanUpFacetedFacesAndEdges();

            // ----------------------------------------------
            //   Menu: Tools->Automation->Journal->Stop Recording
            // ----------------------------------------------

        }
        private void restaurar_pasta()
        {

            NXOpen.Session theSession = NXOpen.Session.GetSession();
            NXOpen.Part workPart = theSession.Parts.Work;
            NXOpen.Part displayPart = theSession.Parts.Display;
            // ----------------------------------------------
            //   Menu: File->Save As...
            // ----------------------------------------------
            NXOpen.PDM.PartOperationCopyBuilder partOperationCopyBuilder1;
            partOperationCopyBuilder1 = theSession.PdmSession.CreateCopyOperationBuilder(NXOpen.PDM.PartOperationBuilder.OperationType.SaveAs);

            partOperationCopyBuilder1.SetOperationSubType(NXOpen.PDM.PartOperationCopyBuilder.OperationSubType.Default);

            partOperationCopyBuilder1.DefaultDestinationFolder = ":Newstuff";

            partOperationCopyBuilder1.Destroy();

        }
        private static Tag GetCell(int row, int column, NXOpen.Annotations.Table _nxTable)

        {

            UFSession.GetUFSession().Tabnot.AskNthRow(_nxTable.Tag, row - 1, out Tag rowTag);

            UFSession.GetUFSession().Tabnot.AskNthColumn(_nxTable.Tag, column - 1, out Tag columnTag);

            UFSession.GetUFSession().Tabnot.AskCellAtRowCol(rowTag, columnTag, out Tag cellTag);

            return cellTag;
        }
        
        public int _simular()
        {
            ////   ATUAL
            int errorCode = 0;
            try
            {
                metodosX.aplicar_config(cmb_dim.ValueAsString.ToString(), dim_larg.Value.ToString().Replace(",", "."), dim_alt.Value.ToString().Replace(",", "."), dim_folga.Value.ToString().Replace(",", "."));
                string[] bitola = cmb_dim.ValueAsString.ToString().Split('x');
                if (invert.Value)
                {
                    metodosX.invert("Invertido", "1");

                    indicador_bitola.Label = bitola[1] + "x" + bitola[0];
                }
                else
                {
                    indicador_bitola.Label = bitola[0] + "x" + bitola[1];
                    metodosX.invert("Arrangement 1", "0");

                }
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                errorCode = 1;
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return errorCode;
        }
        public int _pesquisar()
        {

            while (Resultado.RootNode != null)
            {
                Resultado.DeleteNode(Resultado.RootNode);
            }

            int errorCode = 0;
            try
            {

                metodosX.aplicar_config(cmb_dim.ValueAsString.ToString(), dim_larg.Value.ToString().Replace(",", "."), dim_alt.Value.ToString().Replace(",", "."), dim_folga.Value.ToString().Replace(",", "."));

                if (invert.Value)
                {
                    metodosX.invert("Invertido", "1");
                }
                else
                {
                    metodosX.invert("Arrangement 1", "0");

                }

                result.Clear();
                DataSet busca = metodosX.busca_x(cmb_dim.ValueAsString.ToString(), dim_larg.Value.ToString().Replace(",", "."), dim_alt.Value.ToString().Replace(",", "."), dim_folga.Value.ToString().Replace(",", "."), invert.Value);

                foreach (DataRow dRow in busca.Tables[0].Rows)
                {

                    result.Add(dRow["codigo"].ToString());

                }
                foreach (string res in result)
                {
                    NXOpen.BlockStyler.Node myNode = Resultado.CreateNode(res);
                    Resultado.InsertNode(myNode, null, null, NXOpen.BlockStyler.Tree.NodeInsertOption.Last);
                }
                if(result.Count() == 0)
                {
                    NXOpen.BlockStyler.Node myNode = Resultado.CreateNode("Nenhum item encontrado");
                    Resultado.InsertNode(myNode, null, null, NXOpen.BlockStyler.Tree.NodeInsertOption.Last);
                  
                }
                //}
                //catch (Exception ex)
                //{
                //    ----Enter your exception handling code here---- -
                //    theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
                //}
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                errorCode = 1;
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return errorCode;
        }
        //------------------------------------------------------------------------------
        //Treelist specific callbacks
        //------------------------------------------------------------------------------
        //public void OnExpandCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node)
        //{
        //}

        //public void OnInsertColumnCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
        //{
        //}

        //public void OnInsertNodecallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node)
        //{
        //}

        //public void OnDeleteNodecallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node)
        //{
        //}

        //public void OnPreSelectcallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, bool Selected)
        //{
        //}

        //public void OnSelectcallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, bool Selected)
        //{
        //}

        //public void OnStateChangecallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int State)
        //{
        //}

        //public string ToolTipTextcallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
        //{
        //}

        //public int ColumnSortcallback(NXOpen.BlockStyler.Tree tree, int columnID, NXOpen.BlockStyler.Node node1, NXOpen.BlockStyler.Node node2)
        //{
        //}

        //public string StateIconNameCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int state)
        //{
        //}

        //public Tree.BeginLabelEditState OnBeginLabelEditCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
        //{
        //}

        //public Tree.EndLabelEditState OnEndLabelEditCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, string editedText)
        //{
        //}

        //public Tree.EditControlOption OnEditOptionSelectedCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, int selectedOptionID, string selectedOptionText, Tree.ControlType type)
        //{
        //}

        //public Tree.ControlType AskEditControlCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
        //{
        //}

        //public void OnMenuCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
        //{
        //}

        //public void OnMenuSelectionCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int menuItemID)
        //{
        //}

        //public Node.DropType IsDropAllowedCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, NXOpen.BlockStyler.Node targetNode, int targetColumnID)
        //{
        //}

        //public Node.DragType IsDragAllowedCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
        //{
        //}

        //public bool OnDropCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node[] node, int columnID, NXOpen.BlockStyler.Node targetNode, int targetColumnID, Node.DropType dropType, int dropMenuItemId)
        //{
        //}

        //public void OnDropMenuCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, NXOpen.BlockStyler.Node targetNode, int targetColumnID)
        //{
        //}

        //public void OnDefaultActionCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
        //{
        //}


        //------------------------------------------------------------------------------
        //Function Name: GetBlockProperties
        //Returns the propertylist of the specified BlockID
        //------------------------------------------------------------------------------
        public PropertyList GetBlockProperties(string blockID)
        {
            PropertyList plist = null;
            try
            {
                plist = theDialog.GetBlockProperties(blockID);
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return plist;
        }

    }
}
